version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-sum-{{ checksum "go.sum" }}
      - run: make check
      - run: make run
      - run:
          command: go get -v github.com/int128/ghcp
          working_directory: .circleci
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi
      - save_cache:
          key: go-sum-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
