// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/int128/goxzst/adaptors"
	"github.com/int128/goxzst/usecases"
)

// Injectors from di.go:

func NewCmd() *adaptors.Cmd {
	env := &adaptors.Env{}
	fileSystem := &adaptors.FileSystem{}
	logger := &adaptors.Logger{}
	crossBuild := &usecases.CrossBuild{
		Env:        env,
		FileSystem: fileSystem,
		Logger:     logger,
	}
	archive := &usecases.Archive{
		FileSystem: fileSystem,
		Logger:     logger,
	}
	digest := &usecases.Digest{
		FileSystem: fileSystem,
		Logger:     logger,
	}
	renderTemplate := &usecases.RenderTemplate{
		Env:        env,
		FileSystem: fileSystem,
		Logger:     logger,
	}
	usecasesMake := &usecases.Make{
		CrossBuild:     crossBuild,
		Archive:        archive,
		Digest:         digest,
		RenderTemplate: renderTemplate,
		FileSystem:     fileSystem,
		Logger:         logger,
	}
	cmd := &adaptors.Cmd{
		Make:   usecasesMake,
		Env:    env,
		Logger: logger,
	}
	return cmd
}
